### ISSUE TITLE
Issue where I can't add parts after adding a vendor

### ISSUE THREAD

**Issue by HFreni** [MarSik/elshelves#1]
$ python -m elshelves
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/hfreni/Downloads/elshelves-master/elshelves/__main__.py", line 82, in <module>
    main()
  File "/Users/hfreni/Downloads/elshelves-master/elshelves/**main**.py", line 79, in main
    a.run()
  File "elshelves/app.py", line 178, in run
    pop_ups=True).run()
  File "/usr/local/lib/python2.7/site-packages/urwid-1.3.0-py2.7-macosx-10.10-x86_64.egg/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python2.7/site-packages/urwid-1.3.0-py2.7-macosx-10.10-x86_64.egg/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/site-packages/urwid-1.3.0-py2.7-macosx-10.10-x86_64.egg/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/usr/local/lib/python2.7/site-packages/urwid-1.3.0-py2.7-macosx-10.10-x86_64.egg/urwid/main_loop.py", line 702, in _loop
    ready, w, err = select.select(fds, [], fds)
KeyboardInterrupt

**Comment by MarSik** [comment]
The traceback is a forced quit of the application. Can you explain a bit better what did you try and didn't work?

**Comment by HFreni** [comment]
I quite simply tried adding a part to the database...
